version: '3'
services:
  proxy:
    user: "1000"
    build:
      context: .
      dockerfile: ./development/docker/Dockerfile
    command: bash -c "npm -g install && npm run build && npm run proxy"
    volumes:
      - .:/coco
      - /coco/node_modules
    environment:
      DEV_CONTAINER: 1
    ports:
      - 7777:3000
